import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'INBOX',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'inbox',
        },
      ],
    },
  ],
};

export default sidebars;
