import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Builder sidebar - Case Builder application documentation
  builderSidebar: [
    {
      type: 'autogenerated',
      dirName: 'builder',
    },
  ],
  // Knowledge sidebar - Development knowledge and best practices
  knowledgeSidebar: [
    {
      type: 'autogenerated',
      dirName: 'knowledge',
    },
  ],
  // INBOX sidebar - accessed from header navigation
  inboxSidebar: [
    {
      type: 'autogenerated',
      dirName: 'inbox',
    },
  ],
};

export default sidebars;
