import type { ReactNode } from 'react';
import useBaseUrl from '@docusaurus/useBaseUrl';
import sidebars from '@site/sidebars';
import docTitles from '@site/src/data/doc-titles.json';

type SidebarItem =
  | string
  | {
      type: string;
      label: string;
      items?: SidebarItem[];
      link?: { id: string };
      dirName?: string;
    };

/**
 * Auto-generate display label from sidebar ID
 * Examples:
 *   inboxSidebar → INBOX
 *   builderSidebar → Builder
 *   miscSidebar → Misc
 */
function generateLabel(sidebarId: string): string {
  // Remove "Sidebar" suffix
  const name = sidebarId.replace(/Sidebar$/, '');

  // Special cases
  const specialCases: Record<string, string> = {
    inbox: 'INBOX',
  };

  if (specialCases[name.toLowerCase()]) {
    return specialCases[name.toLowerCase()];
  }

  // Convert camelCase to Title Case
  return name.charAt(0).toUpperCase() + name.slice(1);
}

/**
 * Render a single sidebar item (doc link or category)
 */
function renderSidebarItem(item: SidebarItem, docsBaseUrl: string): ReactNode {
  // String item (doc ID)
  if (typeof item === 'string') {
    const title = docTitles[item as keyof typeof docTitles] || item;
    return (
      <li key={item}>
        <a href={`${docsBaseUrl}${item}`}>{title}</a>
      </li>
    );
  }

  // Category with items
  if (
    typeof item === 'object' &&
    'type' in item &&
    item.type === 'category' &&
    'items' in item &&
    Array.isArray(item.items)
  ) {
    return (
      <li key={item.label}>
        <strong>{item.label}:</strong>
        <ul>{item.items.map((subItem: SidebarItem) => renderSidebarItem(subItem, docsBaseUrl))}</ul>
      </li>
    );
  }

  // Autogenerated - resolve docs from doc-titles.json by dirName prefix
  if (typeof item === 'object' && 'type' in item && item.type === 'autogenerated') {
    const dirName = item.dirName || '';
    const prefix = dirName ? `${dirName}/` : '';
    const matchingDocs = Object.entries(docTitles)
      .filter(([docId]) => docId.startsWith(prefix) && docId !== `${dirName}/index`)
      .sort(([a], [b]) => a.localeCompare(b));

    if (matchingDocs.length === 0) {
      return null;
    }

    return matchingDocs.map(([docId, title]) => (
      <li key={docId}>
        <a href={`${docsBaseUrl}${docId}`}>{title as string}</a>
      </li>
    ));
  }

  return null;
}

export default function DocsSitemap(): ReactNode {
  // Get the base URL for docs (e.g., /docs/)
  const docsBaseUrl = useBaseUrl('/docs/');

  // Auto-generate sidebar list from sidebars.ts (preserves object key order)
  const sidebarEntries = Object.entries(sidebars);

  return (
    <section style={{ marginTop: '3rem' }}>
      <h2>ドキュメント一覧</h2>
      <p style={{ fontSize: '0.9rem', color: '#888', marginBottom: '1rem' }}>
        全ドキュメントページの一覧（sidebars.tsから自動生成）
      </p>

      {sidebarEntries.map(([sidebarId, sidebarItems]) => {
        const label = generateLabel(sidebarId);

        if (!sidebarItems || !Array.isArray(sidebarItems)) {
          return null;
        }

        return (
          <details key={sidebarId} open style={{ marginBottom: '1rem' }}>
            <summary
              style={{
                fontSize: '1.3rem',
                fontWeight: '600',
                padding: '0.5rem 0',
                cursor: 'pointer',
                userSelect: 'none',
                listStyle: 'none',
                display: 'flex',
                alignItems: 'center',
              }}
            >
              <span style={{ marginRight: '0.5rem' }}>▶</span>
              {label}
            </summary>
            <ul style={{ marginTop: '0.5rem' }}>
              {(sidebarItems as SidebarItem[]).map((item) => renderSidebarItem(item, docsBaseUrl))}
            </ul>
          </details>
        );
      })}

      <style>{`
        details[open] > summary > span {
          transform: rotate(90deg);
          display: inline-block;
        }
        details > summary {
          transition: all 0.2s ease;
        }
        details > summary:hover {
          color: var(--ifm-color-primary);
        }
        details > summary > span {
          transition: transform 0.2s ease;
          font-size: 0.8em;
        }
      `}</style>
    </section>
  );
}
